# link: https://jekyllrb.com/docs/configuration/

# Handling Reading
safe                : false
strict_front_matter : true

# Outputting
theme               : jekyll-rtd-theme
title               : dukim-go
description         : dukim-go blog
twitter_username    : DukimD
github_username     : dukim-go
